/**
 * Maps technology/skill names (as they appear in project/work_experience `technologies` arrays)
 * to their display category. Used by the SkillsMatrix aggregation logic.
 *
 * Category keys match the SkillSchema category enum in schema.ts.
 */

export type SkillCategory =
  | 'prog_languages'
  | 'data_languages'
  | 'libraries'
  | 'tools'
  | 'ai_tools'
  | 'vocabularies'
  | 'cloud'
  | 'os'
  | 'design'
  | 'soft_skills'
  | 'personal'
  | 'paradigms'

export const TECH_CATEGORIES: Record<string, SkillCategory> = {
  // ── Programming Languages ──────────────────────────────────────────────────
  Java:           'prog_languages',
  Python:         'prog_languages',
  C:              'prog_languages',
  JavaScript:     'prog_languages',
  TypeScript:     'prog_languages',
  'C#':           'prog_languages',
  Ruby:           'prog_languages',
  'Ruby/Rails':   'prog_languages',
  R:              'prog_languages',
  HTML:           'prog_languages',
  CSS:            'prog_languages',
  Markdown:       'prog_languages',
  Fortran:        'prog_languages',
  Racket:         'prog_languages',
  Assembly:       'prog_languages',
  Lisp:           'prog_languages',
  Julia:          'prog_languages',
  Matlab:         'prog_languages',

  // ── Data Languages ─────────────────────────────────────────────────────────
  OWL:            'data_languages',
  Turtle:         'data_languages',
  TriG:           'data_languages',
  SHACL:          'data_languages',
  SWRL:           'data_languages',
  SPARQL:         'data_languages',
  GeoSPARQL:      'data_languages',
  Cypher:         'data_languages',
  SQL:            'data_languages',
  XML:            'data_languages',
  JSON:           'data_languages',
  CSV:            'data_languages',
  RDF:            'data_languages',
  RDFS:           'data_languages',
  RDFa:           'data_languages',
  'JSON-LD':      'data_languages',
  'JSON Schema':  'data_languages',
  LinkML:         'data_languages',
  GIS:            'data_languages',

  // ── Libraries ──────────────────────────────────────────────────────────────
  PyTorch:              'libraries',
  TensorFlow:           'libraries',
  NumPy:                'libraries',
  Pandas:               'libraries',
  Matplotlib:           'libraries',
  Seaborn:              'libraries',
  Plotly:               'libraries',
  'scikit-learn':       'libraries',
  NLTK:                 'libraries',
  spaCy:                'libraries',
  scispaCy:             'libraries',
  Flair:                'libraries',
  GLiNER:               'libraries',
  'sentence-transformers': 'libraries',
  Transformers:         'libraries',
  'Hugging Face':       'libraries',
  RDFLib:               'libraries',
  SPARQLWrapper:        'libraries',
  LlamaIndex:           'libraries',
  LiteLLM:              'libraries',
  Gradio:               'libraries',
  Streamlit:            'libraries',
  FastAPI:              'libraries',
  Pydantic:             'libraries',
  React:                'libraries',
  'Cytoscape.js':       'libraries',
  Vite:                 'libraries',
  'Apache Jena':        'libraries',
  'OWL API':            'libraries',
  JavaFX:               'libraries',
  JDBC:                 'libraries',
  Numba:                'libraries',
  Numexpr:              'libraries',
  Cython:               'libraries',
  mpi4py:               'libraries',
  MPI:                  'libraries',
  PyMuPDF:              'libraries',
  BeautifulSoup4:       'libraries',
  feedparser:           'libraries',
  PyYAML:               'libraries',
  Typer:                'libraries',
  Rich:                 'libraries',
  PyQt6:                'libraries',
  'Anthropic SDK':      'libraries',
  'OpenAI API':         'libraries',
  OpenAI:               'libraries',
  PyVis:                'libraries',
  'Node.js':            'libraries',
  Fastify:              'libraries',
  pdfplumber:           'libraries',
  PyPDF2:               'libraries',
  Swing:                'libraries',
  JUnit:                'libraries',
  Jackson:              'libraries',
  'json-simple':        'libraries',
  JSoup:                'libraries',

  // ── Tools ──────────────────────────────────────────────────────────────────
  Git:                  'tools',
  GitHub:               'tools',
  Jira:                 'tools',
  Confluence:           'tools',
  Bitbucket:            'tools',
  'Protégé':            'tools',
  GraphDB:              'tools',
  Stardog:              'tools',
  TriplyDB:             'tools',
  Neo4j:                'tools',
  MongoDB:              'tools',
  'Visual Studio Code': 'tools',
  LaTeX:                'tools',
  'Microsoft Word':     'tools',
  'Eclipse IDE':        'tools',
  Eclipse:              'tools',
  MySQL:                'tools',
  PostgreSQL:           'tools',
  PostGIS:              'tools',
  PHPMyAdmin:           'tools',
  QGIS:                 'tools',
  'Jupyter Notebook':   'tools',
  GraphViz:             'tools',
  'Ontotext Refine':    'tools',
  CVAT:                 'tools',
  Docker:               'tools',
  Kubernetes:           'tools',
  Trello:               'tools',
  KuzuDB:               'tools',
  Wikidata:             'tools',
  VxWorks:              'tools',
  Fuseki:               'tools',
  'DL-Learner':         'tools',
  WordPress:            'tools',
  MISTK:                'tools',
  Arduino:              'tools',
  CURL:                 'tools',
  Wireshark:            'tools',
  'Microsoft Teams':    'tools',
  'Microsoft Excel':      'tools',
  'Microsoft PowerPoint': 'tools',
  Signal:               'tools',
  Slack:                'tools',

  // ── AI / ML ────────────────────────────────────────────────────────────────
  Claude:               'ai_tools',
  'Anthropic':          'ai_tools',
  'Anthropic Claude / Claude Code': 'ai_tools',
  'OpenAI GPT series (including API)': 'ai_tools',
  Gemini:               'ai_tools',
  Codex:                'ai_tools',
  Grok:                 'ai_tools',
  'Microsoft Copilot':  'ai_tools',
  Ollama:               'ai_tools',
  'Stable Diffusion':   'ai_tools',
  'SD WebUI':           'ai_tools',
  LoRA:                 'ai_tools',
  Midjourney:           'ai_tools',
  'LM Studio':          'ai_tools',
  Tensorboard:          'ai_tools',
  'Topaz Video AI':     'ai_tools',
  'Hugging Face (platform)': 'ai_tools',
  BERT:                 'ai_tools',
  DistilBERT:           'ai_tools',
  RoBERTa:              'ai_tools',
  ALBERT:               'ai_tools',
  DeBERTa:              'ai_tools',
  VLM:                  'ai_tools',
  NER:                  'ai_tools',
  NLP:                  'ai_tools',
  'Mixture of Agents':  'ai_tools',
  GPT:                  'ai_tools',
  CLIP:                 'ai_tools',
  ResNet:               'ai_tools',
  YOLO:                 'ai_tools',
  AlexNet:              'ai_tools',
  VGGNet:               'ai_tools',

  // ── Ontologies & Vocabularies ──────────────────────────────────────────────
  BFO:          'vocabularies',
  CCO:          'vocabularies',
  SKOS:         'vocabularies',
  'Schema.org': 'vocabularies',
  FOAF:         'vocabularies',
  'PROV-O':     'vocabularies',
  DCTerms:      'vocabularies',
  WordNet:      'vocabularies',
  IAO:          'vocabularies',
  DOLCE:        'vocabularies',
  BIBO:         'vocabularies',
  'SPAR family':'vocabularies',
  SEON:         'vocabularies',
  MLSchema:     'vocabularies',
  UFO:          'vocabularies',
  GFO:          'vocabularies',
  SUMO:         'vocabularies',
  MeSH:         'vocabularies',
  OCSF:           'vocabularies',
  'SNOMED-CT':    'vocabularies',
  GS1:            'vocabularies',
  PROV:           'vocabularies',
  'PROV-ML':      'vocabularies',
  DICO:           'vocabularies',
  JANES:        'vocabularies',
  'SE-ON':      'vocabularies',
  OntoDM:       'vocabularies',
  MEX:          'vocabularies',
  ANNO:         'vocabularies',
  ANNETTO:      'vocabularies',

  // ── Cloud & Deployment ─────────────────────────────────────────────────────
  'GitHub Actions': 'cloud',
  'GitHub Pages':   'cloud',
  'AWS S3':         'cloud',
  'AWS Bedrock':    'cloud',
  'Google Cloud Platform': 'cloud',
  Heroku:           'cloud',
  GoDaddy:          'cloud',

  // ── Operating Systems ──────────────────────────────────────────────────────
  Windows:      'os',
  macOS:        'os',
  Linux:        'os',
  Android:      'os',
  'Google Colab': 'os',
  XigmaNAS:     'os',
  'Kali Linux': 'os',
  RedHat:       'os',
  UNIX:         'os',

  // ── Design & Analysis ──────────────────────────────────────────────────────
  Tableau:      'design',
  RStudio:      'design',
  'Draw.io':    'design',
  Mermaid:      'design',
  LucidChart:   'design',
  Miro:         'design',
  Unity:        'design',
  Kaggle:               'design',
  Figma:                'design',
  Balsamiq:             'design',
  Mockingbird:          'design',

  // ── Data Languages ─── (additional) ────────────────────────────────────────
  TSV:          'data_languages',
  WKT:          'data_languages',

  TCP:                      'tools',
  RAID:                     'tools',
  Chirp:                    'tools',
}
