import type { CompetencyCategory } from './vocab-types'

export const DOMAIN_VOCAB: Record<string, CompetencyCategory> = {
  'Knowledge Graphs':           'domains',
  'Knowledge Representation':   'domains',
  'Knowledge Management':       'domains',
  'Scientific Writing':         'domains',
  'Semantic Web':               'domains',
  'Linked Data':                'domains',
  'FAIR Data':                  'domains',
  Ontology:                     'domains',
  Taxonomy:                     'domains',
  'Machine Learning':           'domains',
  LLMs:                         'domains',
  'Prompt Engineering':         'domains',
  'Text Extraction':            'domains',
  'ML Provenance':              'domains',
  Provenance:                   'domains',
  XAI:                          'domains',
  'Computer Vision':            'domains',
  'Natural Language Processing':'domains',
  'Relationship Extraction':    'domains',
  'Description Logics':         'domains',
  FOL:                          'domains',
  HOL:                          'domains',
  'Software Engineering':       'domains',
  SDLC:                         'domains',
  'Requirements Engineering':   'domains',
  SQA:                          'domains',
  MLOps:                        'domains',
  Embeddings:                   'domains',
  RAG:                          'domains',
  Cybersecurity:                'domains',
  Cryptography:                 'domains',
  Defense:                      'domains',
  Aviation:                     'domains',
  Aerospace:                    'domains',
  Geospatial:                   'domains',
  'Embedded Systems':           'domains',
  'Real-Time Systems':          'domains',
  HPC:                          'domains',
  Networking:                   'domains',
  Education:                    'domains',
  'Web Development':            'domains',
  'Web Scraping':               'domains',
  SEO:                          'domains',
  'Data Analysis':              'domains',
  'Data Visualization':         'domains',
  'Cluster Analysis':           'domains',
  'Game Development':           'domains',
  HCI:                          'domains',
  UX:                           'domains',
  AR:                           'domains',
  Biomedical:                   'domains',
  'Cognitive Science':          'domains',
  'Content Management':         'domains',
  Construction:                 'domains',
  Safety:                       'domains',
  Ethics:                       'domains',
  CLI:                          'domains',
  Quantization:                 'domains',
}
