import type { CompetencyCategory } from './vocab-types'

/** Programming languages, data languages, libraries, tools, AI models, vocabularies, cloud, OS, design. */
export const TECH_VOCAB: Record<string, CompetencyCategory> = {
  // ── Programming Languages ──────────────────────────────────────────────────
  Java:           'prog_languages',
  Python:         'prog_languages',
  Rust:           'prog_languages',
  C:              'prog_languages',
  JavaScript:     'prog_languages',
  TypeScript:     'prog_languages',
  'C#':           'prog_languages',
  Ruby:           'prog_languages',
  'Ruby/Rails':   'prog_languages',
  R:              'prog_languages',
  HTML:           'prog_languages',
  CSS:            'prog_languages',
  Markdown:       'prog_languages',
  Fortran:        'prog_languages',
  Racket:         'prog_languages',
  Assembly:       'prog_languages',
  Lisp:           'prog_languages',
  Julia:          'prog_languages',
  Matlab:         'prog_languages',
  Bash:           'prog_languages',

  // ── Data Languages ─────────────────────────────────────────────────────────
  OWL:            'data_languages',
  Turtle:         'data_languages',
  TriG:           'data_languages',
  SHACL:          'data_languages',
  SWRL:           'data_languages',
  SPARQL:         'data_languages',
  GeoSPARQL:      'data_languages',
  Cypher:         'data_languages',
  SQL:            'data_languages',
  XML:            'data_languages',
  JSON:           'data_languages',
  CSV:            'data_languages',
  RDF:            'data_languages',
  RDFS:           'data_languages',
  RDFa:           'data_languages',
  'JSON-LD':      'data_languages',
  'JSON Schema':  'data_languages',
  LinkML:         'data_languages',
  GIS:            'data_languages',
  TSV:            'data_languages',
  YAML:           'data_languages',
  TOML:           'data_languages',
  WKT:            'data_languages',

  // ── Libraries & Frameworks ─────────────────────────────────────────────────
  Pandoc:               'libraries',
  PyTorch:              'libraries',
  TensorFlow:           'libraries',
  NumPy:                'libraries',
  Pandas:               'libraries',
  Matplotlib:           'libraries',
  Seaborn:              'libraries',
  Plotly:               'libraries',
  'scikit-learn':       'libraries',
  NLTK:                 'libraries',
  spaCy:                'libraries',
  scispaCy:             'libraries',
  Flair:                'libraries',
  'sentence-transformers': 'libraries',
  Transformers:         'libraries',
  'Hugging Face':       'libraries',
  RDFLib:               'libraries',
  SPARQLWrapper:        'libraries',
  LlamaIndex:           'libraries',
  LiteLLM:              'libraries',
  NetworkX:             'libraries',
  Gradio:               'libraries',
  Streamlit:            'libraries',
  FastAPI:              'libraries',
  Pydantic:             'libraries',
  React:                'libraries',
  'Cytoscape.js':       'libraries',
  Vite:                 'libraries',
  'Apache Jena':        'libraries',
  'OWL API':            'libraries',
  JavaFX:               'libraries',
  JDBC:                 'libraries',
  Numba:                'libraries',
  Numexpr:              'libraries',
  Cython:               'libraries',
  mpi4py:               'libraries',
  OpenCV:               'libraries',
  PyMuPDF:              'libraries',
  BeautifulSoup4:       'libraries',
  feedparser:           'libraries',
  PyYAML:               'libraries',
  PyLODE:               'libraries',
  crossterm:            'libraries',
  serde:                'libraries',
  serde_json:           'libraries',
  rand:                 'libraries',
  Typer:                'libraries',
  Rich:                 'libraries',
  PyQt6:                'libraries',
  'Anthropic SDK':      'libraries',
  OpenAI:               'libraries',
  'Node.js':            'libraries',
  Fastify:              'libraries',
  pdfplumber:           'libraries',
  PyPDF2:               'libraries',
  Swing:                'libraries',
  JUnit:                'libraries',
  Jackson:              'libraries',
  'json-simple':        'libraries',
  JSoup:                'libraries',
  Keras:                'libraries',
  Jinja2:               'libraries',
  'Tailwind CSS':       'libraries',
  PostCSS:              'libraries',
  Autoprefixer:         'libraries',
  'Radix UI':           'libraries',
  Zod:                  'libraries',
  'framer-motion':      'libraries',
  'react-helmet-async': 'libraries',
  'react-pdf':          'libraries',
  'react-router':       'libraries',

  // ── Development Tools ──────────────────────────────────────────────────────
  Git:                  'dev_tools',
  GitHub:               'dev_tools',
  Roslyn:               'dev_tools',
  'GitHub CLI':         'dev_tools',
  Jira:                 'dev_tools',
  Confluence:           'dev_tools',
  Bitbucket:            'dev_tools',
  Kanban:               'dev_tools',
  'Protégé':            'dev_tools',
  GraphDB:              'dev_tools',
  Stardog:              'dev_tools',
  TriplyDB:             'dev_tools',
  Neo4j:                'dev_tools',
  MongoDB:              'dev_tools',
  'Visual Studio Code': 'dev_tools',
  Eclipse:              'dev_tools',
  'Code::Blocks':       'dev_tools',
  MySQL:                'dev_tools',
  PostgreSQL:           'dev_tools',
  PostGIS:              'dev_tools',
  PHPMyAdmin:           'dev_tools',
  QGIS:                 'dev_tools',
  'Jupyter Notebook':   'dev_tools',
  GraphViz:             'dev_tools',
  'Ontotext Refine':    'dev_tools',
  CVAT:                 'dev_tools',
  Roboflow:             'dev_tools',
  Docker:               'dev_tools',
  Kubernetes:           'dev_tools',
  Trello:               'dev_tools',
  KuzuDB:               'dev_tools',
  Wikidata:             'dev_tools',
  VxWorks:              'dev_tools',
  Fuseki:               'dev_tools',
  'DL-Learner':         'dev_tools',
  WordPress:            'dev_tools',
  Arduino:              'dev_tools',
  CURL:                 'dev_tools',
  Wireshark:            'dev_tools',
  Unity:                'dev_tools',
  TCP:                  'dev_tools',
  RAID:                 'dev_tools',
  Chirp:                'dev_tools',
  sqlite3:              'dev_tools',

  // ── Office Tools ───────────────────────────────────────────────────────────
  LaTeX:                  'office_tools',
  'Microsoft Word':       'office_tools',
  'Microsoft Excel':      'office_tools',
  'Microsoft PowerPoint': 'office_tools',
  ProPresenter:           'office_tools',
  'Google Docs':          'office_tools',
  'Google Drive':         'office_tools',
  'Google Sheets':        'office_tools',
  'Google Slides':        'office_tools',

  // ── Communication Tools ────────────────────────────────────────────────────
  'Microsoft Teams': 'comm_tools',
  Signal:            'comm_tools',
  Slack:             'comm_tools',
  Discord:           'comm_tools',
  Zoom:              'comm_tools',
  Session:           'comm_tools',

  // ── AI / ML Tools & Models ─────────────────────────────────────────────────
  Claude:              'ai_tools',
  Anthropic:           'ai_tools',
  Gemini:              'ai_tools',
  Codex:               'ai_tools',
  Grok:                'ai_tools',
  'Microsoft Copilot': 'ai_tools',
  Ollama:              'ai_tools',
  'DALL-E':            'ai_tools',
  'Stable Diffusion':  'ai_tools',
  'SD WebUI':          'ai_tools',
  LoRA:                'ai_tools',
  Midjourney:          'ai_tools',
  'LM Studio':         'ai_tools',
  Tensorboard:         'ai_tools',
  'Topaz Video AI':    'ai_tools',
  BERT:                'ai_tools',
  DistilBERT:          'ai_tools',
  RoBERTa:             'ai_tools',
  ALBERT:              'ai_tools',
  DeBERTa:             'ai_tools',
  GLiNER:              'ai_tools',
  VLM:                 'ai_tools',
  NER:                 'ai_tools',
  NLP:                 'ai_tools',
  'Mixture of Agents': 'ai_tools',
  BART:                'ai_tools',
  REBEL:               'ai_tools',
  GPT:                 'ai_tools',
  CLIP:                'ai_tools',
  ResNet:              'ai_tools',
  YOLO:                'ai_tools',
  AlexNet:             'ai_tools',
  VGGNet:              'ai_tools',
  ADE20K:              'ai_tools',
  CIFAR10:             'ai_tools',
  'CIFAR-10':          'ai_tools',
  CIFAR100:            'ai_tools',
  'CIFAR-100':         'ai_tools',
  COCO:                'ai_tools',
  ImageNet:            'ai_tools',
  MNIST:               'ai_tools',
  Places365:           'ai_tools',
  MISTK:               'ai_tools',

  // ── Ontologies, Vocabularies & Standards ──────────────────────────────────
  BFO:            'vocabularies',
  CCO:            'vocabularies',
  SKOS:           'vocabularies',
  'Schema.org':   'vocabularies',
  FOAF:           'vocabularies',
  'PROV-O':       'vocabularies',
  DCTerms:        'vocabularies',
  WordNet:        'vocabularies',
  IAO:            'vocabularies',
  DOLCE:          'vocabularies',
  BIBO:           'vocabularies',
  'SPAR family':  'vocabularies',
  SEON:           'vocabularies',
  MLSchema:       'vocabularies',
  UFO:            'vocabularies',
  GFO:            'vocabularies',
  SUMO:           'vocabularies',
  MeSH:           'vocabularies',
  OCSF:           'vocabularies',
  SWEBOK:         'vocabularies',
  MasterFormat:   'vocabularies',
  SectionFormat:  'vocabularies',
  'MITRE ATT&CK': 'vocabularies',
  'MITRE D3FEND': 'vocabularies',
  'SNOMED-CT':    'vocabularies',
  GS1:            'vocabularies',
  PROV:           'vocabularies',
  'PROV-ML':      'vocabularies',
  DICO:           'vocabularies',
  JANES:          'vocabularies',
  'SE-ON':        'vocabularies',
  OntoDM:         'vocabularies',
  MEX:            'vocabularies',
  ANNO:           'vocabularies',
  ANNETTO:        'vocabularies',
  ECO:            'vocabularies',
  OBI:            'vocabularies',
  RO:             'vocabularies',

  // ── Cloud & Deployment ─────────────────────────────────────────────────────
  'GitHub Actions':        'cloud',
  'GitHub Pages':          'cloud',
  'AWS S3':                'cloud',
  'AWS Bedrock':           'cloud',
  'Google Cloud Platform': 'cloud',
  Heroku:                  'cloud',
  GoDaddy:                 'cloud',

  // ── Operating Systems ──────────────────────────────────────────────────────
  Windows:        'os',
  macOS:          'os',
  Linux:          'os',
  Android:        'os',
  'Google Colab': 'os',
  XigmaNAS:       'os',
  'Kali Linux':   'os',
  RedHat:         'os',
  UNIX:           'os',

  // ── Design & Analysis Tools ────────────────────────────────────────────────
  Tableau:           'design',
  RStudio:           'design',
  'Draw.io':         'design',
  Mermaid:           'design',
  LucidChart:        'design',
  Miro:              'design',
  Kaggle:            'design',
  Figma:             'design',
  Balsamiq:          'design',
  Mockingbird:       'design',
  vMix:              'design',
  'Adobe Photoshop': 'design',
  'Adobe Illustrator': 'design',
}
